# Generated by Django 2.1.dev20171121171147 on 2017-11-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0002_auto_20171125_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamento',
            options={'ordering': ['-data_criacao_orcamento'], 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
    ]
