# Generated by Django 2.1.dev20171121171147 on 2017-11-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0007_auto_20171125_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='JutificativaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_justificativa', models.CharField(max_length=60, verbose_name='Justificativa')),
                ('valor_maximo', models.FloatField(verbose_name='Valor máixmo para o item')),
            ],
            options={
                'verbose_name': 'Justificativa',
                'verbose_name_plural': 'Justificativas',
                'ordering': ['descricao_justificativa'],
            },
        ),
        migrations.CreateModel(
            name='RubricaOrcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rubrica', models.PositiveIntegerField(default=0, verbose_name='Item do orçamento')),
                ('descricao_rubrica', models.TextField(verbose_name='Descrição da rubrica')),
                ('orcamento_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.Orcamento')),
            ],
        ),
    ]
