# Generated by Django 2.1.dev20171121171147 on 2017-11-26 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0020_auto_20171126_1626'),
        ('utils', '0007_unidademedida'),
        ('orcamento', '0008_jutificativaitem_rubricaorcamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubricaorcamento',
            options={'ordering': ['numero_rubrica'], 'verbose_name': 'Rubrica', 'verbose_name_plural': 'Rubricas'},
        ),
        migrations.AddField(
            model_name='jutificativaitem',
            name='codigo_FGV',
            field=models.SmallIntegerField(default=0, verbose_name='Código da tabela FGV'),
        ),
        migrations.AddField(
            model_name='jutificativaitem',
            name='limita_valor',
            field=models.BooleanField(default=False, verbose_name='Limite de valor?'),
        ),
        migrations.AddField(
            model_name='jutificativaitem',
            name='unidade_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.UnidadeMedida'),
        ),
        migrations.AddField(
            model_name='rubricaorcamento',
            name='fase_projeto',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Fase do projeto'),
        ),
        migrations.AddField(
            model_name='rubricaorcamento',
            name='fonte_financiamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projeto.FonteFinanciamento'),
        ),
        migrations.AddField(
            model_name='rubricaorcamento',
            name='grupo_despesa',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Grupo de despesa'),
        ),
        migrations.AddField(
            model_name='rubricaorcamento',
            name='identificacao_rubrica',
            field=models.CharField(max_length=40, null=True, verbose_name='Rubrica'),
        ),
        migrations.AddField(
            model_name='rubricaorcamento',
            name='justificativa_rubrica',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='rubricaorcamento',
            name='provimento',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Provimento'),
        ),
        migrations.AddField(
            model_name='rubricaorcamento',
            name='quantidade',
            field=models.FloatField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='rubricaorcamento',
            name='total',
            field=models.FloatField(default=0, verbose_name='Valor total'),
        ),
        migrations.AddField(
            model_name='rubricaorcamento',
            name='unidade_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.UnidadeMedida'),
        ),
        migrations.AddField(
            model_name='rubricaorcamento',
            name='valor_da_glosa',
            field=models.FloatField(default=0, verbose_name='Valor da glosa'),
        ),
        migrations.AddField(
            model_name='rubricaorcamento',
            name='valor_solicitado',
            field=models.FloatField(default=0, verbose_name='Valor solicitado'),
        ),
        migrations.AlterField(
            model_name='jutificativaitem',
            name='valor_maximo',
            field=models.FloatField(default=0, verbose_name='Valor máixmo'),
        ),
    ]
