# Generated by Django 2.1.dev20171121171147 on 2017-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0009_auto_20171126_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='arquivar',
            field=models.BooleanField(default=False, verbose_name='Arquivar orçamento?'),
        ),
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='fase_projeto',
            field=models.CharField(blank=True, choices=[('PRE', 'Pré-produção'), ('PRO', 'Produção'), ('POS', 'Pós-produção')], max_length=3, null=True, verbose_name='Fase do projeto'),
        ),
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='grupo_despesa',
            field=models.CharField(blank=True, choices=[('EL', 'Elaboração'), ('DV', 'Divulgação'), ('AD', 'Administrativa'), ('PR', 'Produção'), ('OU', 'Outros')], max_length=2, null=True, verbose_name='Grupo de despesa'),
        ),
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='provimento',
            field=models.CharField(blank=True, choices=[('PO', 'Proponente'), ('FT', 'Ficha técnica'), ('PF', 'Terceiros, pessoa física'), ('PJ', 'Terceiros, pessoa jurídica')], max_length=2, null=True, verbose_name='Provimento'),
        ),
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='valor_solicitado',
            field=models.FloatField(default=0, verbose_name='Valor unitário'),
        ),
    ]
