# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0011_auto_20171126_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='orcamento_escolhido',
            field=models.BooleanField(default=False, verbose_name='Orçamento ativo?'),
        ),
    ]
