# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0012_auto_20171128_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubricaorcamento',
            name='total',
        ),
    ]
