# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0030_auto_20171202_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='justificativa_rubrica',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='valor_da_glosa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da glosa R$'),
        ),
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='valor_solicitado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor unitário R$'),
        ),
    ]
