# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0031_auto_20171204_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricaorcamento',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Está ativa?'),
        ),
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='numero_rubrica',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem rubrica'),
        ),
    ]
