# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0034_auto_20171205_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='numero_rubrica',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
