# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_unidademedida'),
        ('orcamento', '0035_auto_20171205_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do pagamento (R$)')),
                ('forma', models.CharField(blank=True, choices=[('CH', 'Cheque'), ('DI', 'Dinheiro'), ('TR', 'Transferência')], default='CH', max_length=2, null=True, verbose_name='Forma de pagamento')),
                ('nr_cheque', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do cheque')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do pagamento')),
                ('tipo_comprovacao', models.CharField(blank=True, choices=[('NF', 'Nota Fiscal'), ('RP', 'RPA Emitida pelo projeto'), ('RB', 'RPA Emitida pelo beneficiário'), ('CP', 'Cupom fiscal')], default='NF', max_length=2, null=True, verbose_name='Tipo de comprovação')),
                ('nr_doc_comprovacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nr documento de comprovação')),
                ('id_pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Pessoa', verbose_name='Beneficiário do pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
