# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0036_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='id_pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Pessoa', verbose_name='Beneficiário'),
        ),
    ]
