# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0037_auto_20171205_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rubrica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.RubricaOrcamento', verbose_name='Rubrica relacionada')),
            ],
        ),
    ]
