# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0038_itempagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempagamento',
            name='id_rubrica',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='id_pessoa',
        ),
        migrations.DeleteModel(
            name='ItemPagamento',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
