# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0039_auto_20171223_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Rubrica ativa?'),
        ),
    ]
