# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0048_auto_20180102_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='valor_concedido',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='valor_solicitado',
        ),
    ]
