# Generated by Django 2.0 on 2018-01-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0051_auto_20180121_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='provimento',
            field=models.CharField(blank=True, choices=[('PO', 'Proponente'), ('TR', 'Terceiros'), ('FT', 'Ficha técnica'), ('PF', 'Terceiros, pessoa física'), ('PJ', 'Terceiros, pessoa jurídica'), ('OU', 'Outros')], max_length=2, null=True, verbose_name='Provimento'),
        ),
    ]
