# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0052_auto_20180126_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricaorcamento',
            name='identificacao_rubrica',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Rubrica'),
        ),
    ]
