# Generated by Django 2.1.dev20171121171147 on 2017-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=200)),
                ('fonte_financiamento', models.CharField(max_length=40)),
                ('edital', models.CharField(max_length=50)),
                ('url_edital', models.URLField()),
                ('inicio_inscricoes', models.DateField()),
                ('fim_inscricoes', models.DateField()),
                ('valor_total', models.FloatField()),
                ('fase_projeto', models.CharField(choices=[('EL', 'Elaboração'), ('DS', 'Desenvolvido'), ('EV', 'Enviado'), ('AN', 'Em análise'), ('RS', 'Recurso seleção'), ('AP', 'Aprovado'), ('AG', 'Aguardando liberação de recursos'), ('PN', 'Pago, mas não iniciado'), ('PE', 'Em execução'), ('PR', 'Pré-produção'), ('PD', 'Produção'), ('PS', 'Pós-produção'), ('EP', 'Elaborando presteação de contas'), ('PC', 'Prestação de contas entregue'), ('AP', 'Análise prestação de contas'), ('PD', 'Pendência prestação de contas'), ('CL', 'Concluído')], max_length=2)),
                ('objeto_contratado', models.TextField()),
                ('resumo', models.TextField()),
                ('area_cultural', models.ForeignKey(null=True, on_delete=None, to='utils.AreaCultural')),
                ('cliente_projeto', models.ForeignKey(null=True, on_delete=None, to='cliente.Cliente')),
            ],
        ),
    ]
