# Generated by Django 2.1.dev20171121171147 on 2017-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('projeto', '0002_remove_projeto_area_cultural'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='area_cultural',
            field=models.ForeignKey(null=True, on_delete=None, to='utils.AreaCultural'),
        ),
    ]
