# Generated by Django 2.1.dev20171121171147 on 2017-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_projeto_area_cultural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='edital',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='fase_projeto',
            field=models.CharField(choices=[('EL', 'Elaboração'), ('DS', 'Desenvolvido'), ('EV', 'Enviado'), ('AN', 'Em análise'), ('RS', 'Recurso seleção'), ('AP', 'Aprovado'), ('AG', 'Aguardando liberação de recursos'), ('PN', 'Pago, mas não iniciado'), ('PE', 'Em execução'), ('PR', 'Pré-produção'), ('PD', 'Produção'), ('PS', 'Pós-produção'), ('EP', 'Elaborando presteação de contas'), ('PC', 'Prestação de contas entregue'), ('AP', 'Análise prestação de contas'), ('PD', 'Pendência prestação de contas'), ('CL', 'Concluído')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='fim_inscricoes',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='fonte_financiamento',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='inicio_inscricoes',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='objeto_contratado',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='resumo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='url_edital',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='valor_total',
            field=models.FloatField(null=True),
        ),
    ]
