# Generated by Django 2.1.dev20171121171147 on 2017-11-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_auto_20171125_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='nome_projeto',
            field=models.CharField(max_length=200, verbose_name='nome do projeto'),
        ),
    ]
