# Generated by Django 2.1.dev20171121171147 on 2017-11-25 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0007_auto_20171125_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-inicio_desenvolvimento'], 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='projeto',
            name='inicio_desenvolvimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data de início do desenvolvimento'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome_projeto',
            field=models.CharField(max_length=200, unique=True, verbose_name='nome do projeto'),
        ),
    ]
