# Generated by Django 2.1.dev20171121171147 on 2017-11-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0008_auto_20171125_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-inicio_desenvolvimento'], 'verbose_name_plural': 'Projetos'},
        ),
    ]
