# Generated by Django 2.1.dev20171121171147 on 2017-11-26 00:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0013_auto_20171125_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_orcamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Particulariza do orçamento')),
                ('valor_solicitado', models.FloatField(blank=True, null=True, verbose_name='Valor solicitado')),
                ('valor_concedido', models.FloatField(blank=True, null=True, verbose_name='Valor concedido')),
                ('limite_proponente', models.FloatField(blank=True, null=True, verbose_name='Limite do proponente')),
                ('limite_minimo_divulgacao', models.FloatField(blank=True, null=True, verbose_name='Limite mínimo para divulgação')),
                ('limite_administracao', models.FloatField(blank=True, null=True, verbose_name='Limite máximo para administração')),
                ('percentual_pre_producao', models.FloatField(blank=True, null=True, verbose_name='Limite pré-produção(%)')),
                ('percentual_producao', models.FloatField(blank=True, null=True, verbose_name='Limite     produção(%)')),
                ('percentual_pos_producao', models.FloatField(blank=True, null=True, verbose_name='Limite pós-produção')),
                ('percentual_elaboracao_captacao', models.FloatField(blank=True, null=True, verbose_name='Limite elaboração ou captação')),
                ('limite_total', models.FloatField(blank=True, null=True, verbose_name='Valor limite do orçamento')),
                ('orcamento_escolhido', models.BooleanField(default=False, verbose_name='Orçamento aprovado?')),
                ('agrega_tipo_despesa', models.BooleanField(default=False, verbose_name='Agregar por tipo de despesa?')),
                ('agrega_fase_projeto', models.BooleanField(default=False, verbose_name='Agregar por fase de projeto?')),
                ('agrega_por_fonte', models.BooleanField(default=False, verbose_name='Agregar por fonte de financiamento?')),
                ('data_criacao_orcamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e hora da criação')),
                ('projeto_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto')),
            ],
            options={
                'verbose_name_plural': 'Orçamento do projeto ALGUMA COISA - VAI PRECISAR RESOLVER',
                'ordering': ['-data_criacao_orcamento'],
            },
        ),
    ]
