# Generated by Django 2.1.dev20171121171147 on 2017-11-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0017_auto_20171125_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='projeto_associado',
        ),
        migrations.DeleteModel(
            name='Orcamento',
        ),
    ]
