# Generated by Django 2.1.dev20171121171147 on 2017-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0021_auto_20171126_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='arquivar',
            field=models.BooleanField(default=False, verbose_name='Arquivar projeto?'),
        ),
    ]
