# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0025_auto_20171228_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='percentual_ISS',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='precentual_INSS',
        ),
    ]
