# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0035_auto_20180114_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='tarefa',
            new_name='desricao_tarefa',
        ),
    ]
