# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0036_auto_20180114_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='desricao_tarefa',
            field=models.TextField(verbose_name='Descrição da tarefa'),
        ),
    ]
