# Generated by Django 2.0 on 2018-01-26 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0037_auto_20180114_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='projeto.Meta', verbose_name='Meta associada'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Pessoa'),
        ),
    ]
