# Generated by Django 2.0 on 2018-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0039_auto_20180205_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='nr_processo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº do processo ou contrato'),
        ),
    ]
