# Generated by Django 2.1.dev20171121171147 on 2017-11-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.Pessoa')),
                ('ceac', models.CharField(blank=True, max_length=4, null=True)),
                ('curriculo', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('area_cultural', models.ForeignKey(blank=True, null=True, on_delete=None, to='utils.AreaCultural')),
            ],
            bases=('utils.pessoa',),
        ),
    ]
