# Generated by Django 2.1.dev20171121171147 on 2017-11-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='area_cultural',
        ),
    ]
