# Generated by Django 2.1.dev20171121171147 on 2017-11-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('cliente', '0002_remove_cliente_area_cultural'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='area_cultural',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='utils.AreaCultural'),
        ),
    ]
