# Generated by Django 2.1.dev20171121171147 on 2017-11-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20171125_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
