# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0009_tabelairrf'),
        ('orcamento', '0039_auto_20171223_2032'),
        ('projeto', '0024_auto_20171205_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaComprovacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprovacao', models.CharField(blank=True, choices=[('NF', 'Nota Fiscal'), ('RP', 'RPA Emitida pelo projeto'), ('RB', 'RPA Emitida pelo beneficiário'), ('CP', 'Cupom fiscal')], default='NF', max_length=2, null=True, verbose_name='Tipo de comprovação')),
                ('nr_doc_comprovacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nr documento de comprovação')),
                ('observacao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='FormaDePagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(blank=True, choices=[('CH', 'Cheque'), ('DI', 'Dinheiro'), ('TR', 'Transferência')], default='CH', max_length=2, null=True, verbose_name='Forma de pagamento')),
                ('nr_documento', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nr. documento (cheque, transf., etc)')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do pagamento (R$)')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da emissão')),
                ('data_efetivacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da efetivação')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantidade')),
                ('valor_bruto_pagamento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor a pagar (R$)')),
                ('cobrar_ISS', models.BooleanField(default=False, verbose_name='Cobrar ISS?')),
                ('valor_ISS', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do ISS')),
                ('cobrar_INSS', models.BooleanField(default=False, verbose_name='Cobrar ISS?')),
                ('valor_INSS', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do INSS')),
                ('cobrar_IR', models.BooleanField(default=False, verbose_name='Cobrar Imposto de Renda?')),
                ('valor_IR', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Imposto')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do pagamento')),
                ('pendente', models.BooleanField(default=True, verbose_name='Pagamento pendente?')),
                ('observacoes', models.TextField(blank=True, max_length=200, null=True, verbose_name='Observações')),
                ('id_orcamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.Orcamento', verbose_name='Orçamento relacionado')),
                ('id_pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Pessoa', verbose_name='Beneficiário')),
                ('id_projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto', verbose_name='Projeto relacionado')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.AddField(
            model_name='itempagamento',
            name='id_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagamento.Pagamento'),
        ),
        migrations.AddField(
            model_name='itempagamento',
            name='id_rubrica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orcamento.RubricaOrcamento', verbose_name='Rubrica relacionada'),
        ),
        migrations.AddField(
            model_name='formadepagamento',
            name='id_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagamento.Pagamento'),
        ),
        migrations.AddField(
            model_name='formacomprovacao',
            name='id_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagamento.Pagamento'),
        ),
    ]
