# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0002_auto_20171226_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempagamento',
            name='cobrar_ISS',
            field=models.BooleanField(default=False, verbose_name='Cobra ISS?'),
        ),
    ]
