# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0003_auto_20171226_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempagamento',
            name='cobrar_INSS',
        ),
        migrations.RemoveField(
            model_name='itempagamento',
            name='cobrar_IR',
        ),
        migrations.RemoveField(
            model_name='itempagamento',
            name='cobrar_ISS',
        ),
        migrations.RemoveField(
            model_name='itempagamento',
            name='valor_INSS',
        ),
        migrations.RemoveField(
            model_name='itempagamento',
            name='valor_IR',
        ),
        migrations.RemoveField(
            model_name='itempagamento',
            name='valor_ISS',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='cobrar_INSS',
            field=models.BooleanField(default=False, verbose_name='Cobrar INSS?'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='cobrar_IR',
            field=models.BooleanField(default=False, verbose_name='Cobrar Imposto de Renda?'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='cobrar_ISS',
            field=models.BooleanField(default=False, verbose_name='Cobra ISS?'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_INSS',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do INSS'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_IR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Imposto'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_ISS',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do ISS'),
        ),
    ]
