# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0004_auto_20171226_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='pendente',
            field=models.BooleanField(default=True, verbose_name='Pagamento está pendente?'),
        ),
    ]
