# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0005_auto_20171226_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='valor_INSS',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='valor_IR',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='valor_ISS',
        ),
    ]
