# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0006_auto_20171228_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='cobrar_IR',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='cobrar_ISS',
            field=models.BooleanField(default=True, verbose_name='Cobra ISS?'),
        ),
    ]
