# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0007_auto_20171228_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacomprovacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do documento(R$)'),
        ),
    ]
