# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0008_formacomprovacao_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacomprovacao',
            name='observacao',
        ),
        migrations.AddField(
            model_name='formacomprovacao',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da emissão'),
        ),
    ]
