# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import pagamento.models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0009_auto_20171229_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempagamento',
            name='valor_bruto_pagamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor a pagar (R$)'),
        ),
    ]
