# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0013_auto_20171230_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formadepagamento',
            name='forma',
            field=models.CharField(choices=[('CH', 'Cheque'), ('DI', 'Dinheiro'), ('TR', 'Transferência')], default='CH', max_length=2, null=True, verbose_name='Forma de pagamento'),
        ),
    ]
