# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0014_auto_20171231_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formadepagamento',
            name='nr_documento',
            field=models.PositiveIntegerField(null=True, verbose_name='Nr. documento (cheque, transf., etc)'),
        ),
        migrations.AlterField(
            model_name='formadepagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor desta forma pagamento (R$)'),
        ),
    ]
