# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0017_auto_20171231_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formadepagamento',
            name='valor',
            field=models.FloatField(default=0.0, verbose_name='Valor desta forma pagamento (R$)'),
        ),
    ]
