# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0018_auto_20171231_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formadepagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor desta forma pagamento (R$)'),
        ),
    ]
