# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0021_auto_20171231_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacomprovacao',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do recebimento'),
        ),
        migrations.AlterField(
            model_name='formacomprovacao',
            name='nr_doc_comprovacao',
            field=models.CharField(max_length=15, null=True, verbose_name='Nr documento de comprovação'),
        ),
    ]
