# Generated by Django 2.0 on 2018-01-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0024_auto_20180103_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempagamento',
            name='id_rubrica',
            field=models.ForeignKey(null=True, on_delete=None, to='orcamento.RubricaOrcamento', verbose_name='Rubrica relacionada'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id_orcamento',
            field=models.ForeignKey(null=True, on_delete=None, to='orcamento.Orcamento', verbose_name='Orçamento relacionado'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id_pessoa',
            field=models.ForeignKey(null=True, on_delete=None, to='utils.Pessoa', verbose_name='Beneficiário'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id_projeto',
            field=models.ForeignKey(null=True, on_delete=None, to='projeto.Projeto', verbose_name='Projeto relacionado'),
        ),
    ]
