# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0025_auto_20180126_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data_efetivacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do efetivação'),
        ),
    ]
