# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0026_pagamento_data_efetivacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data_lancamento'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='data_efetivacao',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='data_pagamento',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_lancamento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do lançamento'),
        ),
    ]
