# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0027_auto_20180208_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formadepagamento',
            name='data_emissao',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data da emissão'),
        ),
    ]
