# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0030_auto_20180213_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacomprovacao',
            name='descricao_comprovacao',
            field=models.TextField(blank=True, verbose_name='Descrição conforme documento fiscal:'),
        ),
    ]
