# Generated by Django 2.1.dev20171121171147 on 2017-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCultural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_cultural', models.CharField(max_length=30, unique=True)),
                ('sub_area', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('fone1', models.CharField(blank=True, max_length=40, null=True)),
                ('fone2', models.CharField(blank=True, max_length=40, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cpfoucnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('identidadeouinscricao', models.CharField(blank=True, max_length=30, null=True)),
                ('redesocial', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
