# Generated by Django 2.1.dev20171121171147 on 2017-11-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacultural',
            name='area_cultural',
            field=models.CharField(max_length=30, unique=True, verbose_name='área cultural'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpfoucnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF ou CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='endereço completo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='fone1',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='fone (1)'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='fone2',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='fone (2)'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='identidadeouinscricao',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Identidade ou Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='redesocial',
            field=models.URLField(blank=True, null=True, verbose_name='Link rede social'),
        ),
    ]
