# Generated by Django 2.1.dev20171121171147 on 2017-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20171125_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='pessoa_fisica',
            field=models.BooleanField(default=True, verbose_name='pessoa física'),
        ),
    ]
