# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_unidademedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='fone1',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Fone (1)'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='fone2',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Fone (2)'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome/razão social'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pessoa_fisica',
            field=models.BooleanField(default=True, verbose_name='Pessoa física?'),
        ),
    ]
