# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_auto_20171208_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaIRRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
