# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_tabelairrf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliquotaINSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Percentual')),
                ('local_cobrança', models.CharField(blank=True, max_length=30, null=True, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='AliquotaISS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Percentual')),
                ('local_cobrança', models.CharField(blank=True, max_length=20, null=True, verbose_name='Local de cobrança')),
            ],
        ),
    ]
