# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 17:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_aliquotainss_aliquotaiss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabelairrf',
            options={'ordering': ['-ano'], 'verbose_name': 'Tabela de IRRF', 'verbose_name_plural': 'Tabelas de IRRF'},
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='aliquota_faixa2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Aliquota 2a faixa'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='aliquota_faixa3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Aliquota 3a faixa'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='aliquota_faixa4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Aliquota 4a faixa'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='aliquota_faixa5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Aliquota 5a faixa'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='ano',
            field=models.PositiveIntegerField(default=2017, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2017)], verbose_name='Ano base'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Tabela ativa?'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='deducao_faixa2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Dedução 2a faixa'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='deducao_faixa3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Dedução 3a faixa'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='deducao_faixa4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Dedução 4a faixa'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='deducao_faixa5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Dedução 5a faixa'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='limite_faixa1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Limite isenção'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='limite_faixa2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Limite 2a faixa'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='limite_faixa3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Limite 3a faixa'),
        ),
        migrations.AddField(
            model_name='tabelairrf',
            name='limite_faixa4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Limite 4a faixa'),
        ),
    ]
