# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_auto_20171228_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelairrf',
            name='aliquota_faixa2',
            field=models.FloatField(default=0, verbose_name='Aliquota 2a faixa'),
        ),
        migrations.AlterField(
            model_name='tabelairrf',
            name='aliquota_faixa3',
            field=models.FloatField(default=0, verbose_name='Aliquota 3a faixa'),
        ),
        migrations.AlterField(
            model_name='tabelairrf',
            name='aliquota_faixa4',
            field=models.FloatField(default=0, verbose_name='Aliquota 4a faixa'),
        ),
        migrations.AlterField(
            model_name='tabelairrf',
            name='aliquota_faixa5',
            field=models.FloatField(default=0, verbose_name='Aliquota 5a faixa'),
        ),
        migrations.AlterField(
            model_name='tabelairrf',
            name='deducao_faixa2',
            field=models.FloatField(default=0, verbose_name='Dedução 2a faixa'),
        ),
        migrations.AlterField(
            model_name='tabelairrf',
            name='deducao_faixa3',
            field=models.FloatField(default=0, verbose_name='Dedução 3a faixa'),
        ),
        migrations.AlterField(
            model_name='tabelairrf',
            name='deducao_faixa4',
            field=models.FloatField(default=0, verbose_name='Dedução 4a faixa'),
        ),
        migrations.AlterField(
            model_name='tabelairrf',
            name='deducao_faixa5',
            field=models.FloatField(default=0, verbose_name='Dedução 5a faixa'),
        ),
        migrations.AlterField(
            model_name='tabelairrf',
            name='limite_faixa1',
            field=models.FloatField(default=0, verbose_name='Limite isenção'),
        ),
        migrations.AlterField(
            model_name='tabelairrf',
            name='limite_faixa2',
            field=models.FloatField(default=0, verbose_name='Limite 2a faixa'),
        ),
        migrations.AlterField(
            model_name='tabelairrf',
            name='limite_faixa3',
            field=models.FloatField(default=0, verbose_name='Limite 3a faixa'),
        ),
        migrations.AlterField(
            model_name='tabelairrf',
            name='limite_faixa4',
            field=models.FloatField(default=0, verbose_name='Limite 4a faixa'),
        ),
    ]
