# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descreva o arquivo')),
                ('arquivo_carga', models.FileField(upload_to='', verbose_name='Carregar arquivo')),
                ('data_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
