# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='descricao',
            field=models.TextField(verbose_name='Descreva o arquivo'),
        ),
    ]
