# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0002_auto_20180118_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo_carga',
            field=models.FileField(upload_to='orcamentos/', verbose_name='Carregar arquivo'),
        ),
    ]
