# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0003_auto_20180118_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_funcao_arquivo', models.CharField(max_length=25, verbose_name='Função do arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoArquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_tipo_arquivo', models.CharField(max_length=75, verbose_name='Descrição do tipo de arquivo')),
                ('extencao_arquivo', models.CharField(max_length=4, verbose_name='Extenção do tipo de arquivo')),
            ],
        ),
        migrations.AddField(
            model_name='arquivo',
            name='funcao_arquivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carregaarquivo.FuncaoArquivo', verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='tipo_arquivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carregaarquivo.TipoArquivo', verbose_name='Tipo de arquivo'),
        ),
    ]
