# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0004_auto_20180118_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcaoarquivo',
            name='descricao_funcao_arquivo',
            field=models.CharField(max_length=50, verbose_name='Função do arquivo'),
        ),
    ]
