# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0005_auto_20180118_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivo',
            options={'ordering': ['-data_uploaded'], 'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AlterModelOptions(
            name='funcaoarquivo',
            options={'ordering': ['descricao_funcao_arquivo'], 'verbose_name': 'Função do Arquivo', 'verbose_name_plural': 'Funções dos Arquivos'},
        ),
        migrations.AlterModelOptions(
            name='tipoarquivo',
            options={'ordering': ['descricao_tipo_arquivo'], 'verbose_name': 'Tipo de Arquivo', 'verbose_name_plural': 'Tipos de Arquivos'},
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo_carga',
            field=models.FileField(upload_to='', verbose_name='Carregar arquivo'),
        ),
    ]
