# Generated by Django 2.0 on 2018-01-26 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0007_funcaoarquivo_sigla_funcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroImportacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filtro', models.CharField(max_length=40, verbose_name='Nome do filtro')),
                ('descricao_filtro', models.TextField(blank=True, verbose_name='Descrição da função do filtro')),
                ('linha_inicial', models.PositiveIntegerField(default=0, verbose_name='Linha inicial')),
                ('linha_final', models.PositiveIntegerField(default=20, verbose_name='Linha inicial')),
                ('coluna_inicial', models.CharField(default='A', max_length=3, verbose_name='Coluna inicial')),
                ('coluna_final', models.CharField(default='L', max_length=3, verbose_name='Coluna final')),
                ('excecao_linhas', models.CharField(blank=True, max_length=50, verbose_name='Linhas que não devem ser processadas')),
                ('excecao_colunas', models.CharField(blank=True, max_length=50, verbose_name='Colunas que não devem ser processadas')),
                ('tipo_arquivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carregaarquivo.TipoArquivo', verbose_name='Se aplica a que tipo de arquivo?')),
            ],
            options={
                'verbose_name': 'Filtro de importação',
                'verbose_name_plural': 'Filtro de importações',
                'ordering': ['nome_filtro'],
            },
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='funcao_arquivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carregaarquivo.FuncaoArquivo', verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tipo_arquivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carregaarquivo.TipoArquivo', verbose_name='Tipo de arquivo'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='filtro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carregaarquivo.FiltroImportacao', verbose_name='Filtro de importação'),
        ),
    ]
