# Generated by Django 2.0 on 2018-01-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0008_auto_20180126_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtroimportacao',
            name='linha_final',
            field=models.PositiveIntegerField(default=20, verbose_name='Linha final'),
        ),
    ]
