# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0009_auto_20180126_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAlvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modelo', models.CharField(max_length=25, verbose_name='Nome do modelo alvo')),
                ('app_modelo', models.CharField(max_length=50, verbose_name='Aplicativo do modelo')),
            ],
            options={
                'verbose_name': 'Modelo alvo',
                'verbose_name_plural': 'Modelos alvos',
                'ordering': ['nome_modelo'],
            },
        ),
        migrations.AddField(
            model_name='filtroimportacao',
            name='funcoes_colunas',
            field=models.CharField(blank=True, max_length=50, verbose_name='Quais as funções que serão aplicadas as colunas'),
        ),
        migrations.AddField(
            model_name='filtroimportacao',
            name='funcoes_linhas',
            field=models.CharField(blank=True, max_length=50, verbose_name='Quais as funções que serão aplicadas as linhas'),
        ),
        migrations.AddField(
            model_name='filtroimportacao',
            name='modelo_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carregaarquivo.ModeloAlvo', verbose_name='Nome da tabela de destino'),
        ),
    ]
