# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0010_auto_20180127_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtroimportacao',
            name='correspondencias_campos',
            field=models.TextField(blank=True, verbose_name='Correspondência entre campos e colunas planilha'),
        ),
        migrations.AlterField(
            model_name='filtroimportacao',
            name='funcoes_colunas',
            field=models.TextField(blank=True, verbose_name='Quais as funções que serão aplicadas as colunas'),
        ),
        migrations.AlterField(
            model_name='filtroimportacao',
            name='funcoes_linhas',
            field=models.TextField(blank=True, verbose_name='Quais as funções que serão aplicadas as linhas'),
        ),
    ]
