# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0011_auto_20180128_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='objeto_associado',
            field=models.PositiveIntegerField(default=0, verbose_name='Objeto associado'),
        ),
    ]
