# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0012_arquivo_objeto_associado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='objeto_associado',
            field=models.IntegerField(choices=[(0, 'Não existe objeto definido')], default=0, verbose_name='Objeto associado'),
        ),
    ]
