# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0013_auto_20180128_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='objeto_associado',
            field=models.IntegerField(choices=[(1, 'Projeto1'), (1, 'Não existe objeto definido 2')], default=0, verbose_name='Objeto associado'),
        ),
    ]
