# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0014_auto_20180128_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='objeto_associado',
            field=models.IntegerField(default=0, verbose_name='Objeto associado'),
        ),
    ]
