# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0016_auto_20180128_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='objeto_associado',
            field=models.CharField(choices=[('0', 'Não existe objeto definido'), ('1', 'Não existe objeto definido 2')], default='0', max_length=3, verbose_name='Objeto associado'),
        ),
    ]
