# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0021_auto_20180128_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='objeto_associado',
        ),
    ]
