# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0022_remove_arquivo_objeto_associado'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='objeto_associado',
            field=models.CharField(default='0', max_length=3, verbose_name='Objeto associado'),
        ),
    ]
