# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0023_arquivo_objeto_associado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='objeto_associado',
            field=models.CharField(blank=True, choices=[('Projeto.Maria Maria.pk=3', 'Maria Maria'), ('Projeto.Zumbi babão.pk=4', 'Zumbi babão'), ('Projeto.Todos os homens do presidente.pk=2', 'Todos os homens do presidente'), ('Projeto.Todo.pk=1', 'Todo')], default='0', max_length=60, verbose_name='Objeto associado'),
        ),
    ]
