# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0024_auto_20180128_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='objeto_associado',
            field=models.CharField(blank=True, default='0', max_length=60, verbose_name='Objeto associado'),
        ),
    ]
