# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0025_auto_20180129_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='objeto_associado',
            field=models.CharField(blank=True, default='0', max_length=60, verbose_name='Relacionado com o objeto'),
        ),
    ]
