# Generated by Django 2.0 on 2018-01-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carregaarquivo', '0026_auto_20180129_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='objeto_associado',
            field=models.CharField(blank=True, default='0', max_length=60),
        ),
    ]
